### ISSUE TITLE
Update Software Architecture Diagrams

### ISSUE THREAD

**Issue by Alexicazana** [WillTrem/UInnovate#44]
-Overall Software Arch: Per the stakeholder's review of our overall software architecture diagram, some changes need to be made to include some more information. Refer to picture below of the Excalidraw document, which aims to give a more detailed understanding of how each layer (backend, frontend, db) interacts with one another as well as how the system works overall.
<img width="706" alt="Screenshot 2023-10-26 at 3 37 04 PM" src="https://github.com/WillTrem/UInnovate/assets/55753055/96c9ec3c-37f3-447f-8d81-59240804d1d8">

-Class Diagram: Create a class diagram using the current use case. As per the TAs requirements, if a class diagram feels too unfitting given the nature of our project, we must provide him with enough reasoning to justify the choice of not creating a class diagram, should we decide instead to create an alternate software architecture diagram that better suits our needs. Some suggestions from the TA: "If you determine that it is not possible, do the next best thing and add justification on why you chose to represent your project in a particular way. If it’s not a requirement but you are doing this to understand the project better, I would go with a data flow diagram (as you mentioned “consider doing a data flow diagram, or a flowchart of a visual representation of how data is supposed to flow through our system instead”)."
My personal recommendation having spent some time trying to create a class diagram is to **opt for a data flow diagram instead**,  and provide justification, as this would be more useful to us.

**Comment by AfandiM** [comment]
I updated the overall architecture diagram to better fit the vision we have for the UInnovate App: added some of the main files that are used in the app, as well as more detailed connections between the major components.

![image](https://github.com/WillTrem/UInnovate/assets/84986555/64de122a-8f8e-4a53-86f9-971741afa83b)

Additionally, I decided to draw a data flow diagram rather than a class diagram to represent the system: by design, the UInnovate application lacks the concept of a "class", and is rather focused on the flow of data between semi-dependent entities.

![image](https://github.com/WillTrem/UInnovate/assets/84986555/cdeef176-83ce-44ba-a984-4b6b5232bf6d)

**Comment by lyubageorgieva** [comment]
This Task was converted into a US #53, and the US has been closed.
