### ISSUE TITLE
[US] Set up the view configuration loading

### ISSUE THREAD

**Issue by AfandiM** [WillTrem/UInnovate#58]
As an application configurator, I want the application's configuration to be applied to the application so that it reflects out preferences and needs regarding data visualization

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must |   High                   |      8             |

## Acceptance Criteria
- View configuration stored in database
- View configuration loaded onto VMD from application load
- VMD only displays data according to the view configuration
- VMD refresh button properly refreshes view configuration
## Risks
- Complexity of tabularizing view configurations
- Complexity of loading view configurations onto VMD
## Tasks
- [ ] Backend configuration fetching with PostgREST
- [x] #77

## Note
**The application configuration part of this user story is tightly related to US #19, highly recommend coordinating with the relevant developers**

**Comment by Alexicazana** [comment]
I created a simple high-level diagram to show what are the relevant interactions between the different parts of the system for this feature. It's useful for me to reference it, and for onboarding teammates easier.

![Screenshot 2023-11-14 at 2 39 30 AM](https://github.com/WillTrem/UInnovate/assets/55753055/8044d517-3f86-40cd-9aa1-c768ea0c7ff3)

**Comment by Alexicazana** [comment]
1. **Database Schema Review and Update**:

   - Ensure that the `appconfig_values` and `appconfig_properties` tables in the database are structured to store the necessary configuration settings.
   - ensure default values to the `appconfig_properties` table are available.

2. **Backend Configuration Fetching**:

   - Create or update backend endpoints (using PostgREST) to fetch configuration settings from the database. (instead of everyone doing this) -> main most important feature of this US (**MVF**)
   - Include logic to handle default values for any settings that are not explicitly set. 

3. **Frontend Integration**:

   - Update the Settings page to interact with the new backend endpoints for fetching configuration settings. (**MVF**)
   - Implement UI elements (such as toggles or dropdowns) to allow users to view and modify the visibility of tables and columns.

4. **Virtual Model Definition (VMD) Update**:

   - Modify the VMD to dynamically reflect the configuration settings.
   - Ensure that the VMD only displays data according to the view configuration.

5. **Implementing a Refresh Mechanism**:

   - Add a refresh button on the UI that triggers a re-fetch of the configuration settings.
   - Ensure that the VMD updates accordingly when the refresh button is used.

6. **Testing and Validation**:

   - Write unit tests to validate the behavior of the new backend endpoints and the default value logic.
   - Test the integration on the frontend to ensure that the configuration settings are correctly applied and that the VMD behaves as expected.
   - Validate that the acceptance criteria are met.

**Comment by lyubageorgieva** [comment]
Deprecated
